-- Profiles Table DDL
CREATE TABLE IF NOT EXISTS profiles (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id INT UNIQUE NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(20),
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    college VARCHAR(255),
    university VARCHAR(255),
    qualification VARCHAR(100),
    branch VARCHAR(100),
    cgpa DECIMAL(4,2),
    graduation_year INT,
    skills TEXT,
    experience_years DECIMAL(4,1) DEFAULT 0.0,
    current_company VARCHAR(150),
    current_role VARCHAR(150),
    previous_companies TEXT,
    projects TEXT,
    certifications TEXT,
    linkedin_url VARCHAR(255),
    github_url VARCHAR(255),
    portfolio_url VARCHAR(255),
    profile_photo VARCHAR(255),
    completion_percentage INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
